name: ua_client_hins_sample_app
description: Demonstrates how to use the ua_client_hints plugin.

version: 1.0.0+1

publish_to: 'none'

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  ua_client_hints:
    path: ../

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
