# git-cliff ~ configuration file
# https://git-cliff.org/docs/configuration

[changelog]
header = """
# Changelog

All notable changes to this project will be documented in this file.

The format is based on [Keep a Changelog](https://keepachangelog.com/en/1.1.0/),
and this project adheres to [Semantic Versioning](https://semver.org/spec/v2.0.0.html).

"""
body = """
{% if version -%}
    ## [{{ version | trim_start_matches(pat="v") }}] - {{ timestamp | date(format="%Y-%m-%d") }}
{% else -%}
    ## [Unreleased]
{% endif -%}
{% for group, commits in commits | group_by(attribute="group") %}
    {% if group == "Added" %}
        ### Added
    {% elif group == "Changed" %}
        ### Changed
    {% elif group == "Deprecated" %}
        ### Deprecated
    {% elif group == "Removed" %}
        ### Removed
    {% elif group == "Fixed" %}
        ### Fixed
    {% elif group == "Security" %}
        ### Security
    {% else %}
        ### {{ group | upper_first }}
    {% endif %}
    {% for commit in commits -%}
        - {{ commit.message | split(pat="\n") | first | trim }}
    {% endfor %}
{% endfor %}\n
"""
footer = """
{% for release in releases -%}
    {% if release.version -%}
        {% if release.previous.version -%}
            [{{ release.version | trim_start_matches(pat="v") }}]: \
                https://github.com/{{ remote.github.owner }}/{{ remote.github.repo }}\
                    /compare/{{ release.previous.version }}..{{ release.version }}
        {% endif -%}
    {% else -%}
        [unreleased]: https://github.com/{{ remote.github.owner }}/{{ remote.github.repo }}\
            /compare/{{ release.previous.version }}..HEAD
    {% endif -%}
{% endfor %}
<!-- generated by git-cliff -->
"""
trim = true

[git]
conventional_commits = true
filter_unconventional = false
commit_parsers = [
    { message = "^feat", group = "Added" },
    { message = "^add", group = "Added" },
    { message = "^support", group = "Added" },
    { message = "^fix", group = "Fixed" },
    { message = "^perf", group = "Fixed" },
    { message = "^refactor", group = "Changed" },
    { message = "^style", group = "Changed" },
    { message = "^test", group = "Changed" },
    { message = "^chore", group = "Changed" },
    { message = "^docs", group = "Changed" },
    { message = "^ci", group = "Changed" },
    { message = "^build", group = "Changed" },
    { message = "^remove", group = "Removed" },
    { message = "^delete", group = "Removed" },
    { message = ".*deprecated", group = "Deprecated" },
    { message = ".*security", group = "Security" },
    { message = "^.*", group = "Changed" },
]
filter_commits = false
topo_order = false
sort_commits = "oldest"
