name: Flutter CI

on:
  pull_request: { }
  push:
    branches:
      - 'main'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.4.0
      - uses: subosito/flutter-action@v1
        with:
          flutter-version: '2.5.2'
      - uses: dart-lang/setup-dart@v1
        with:
          sdk: '2.14.3'

      - name: Cache Gradle modules
        uses: actions/cache@v3.0.1
        env:
          cache-number: ${{ secrets.CACHE_NUMBER }}
        with:
          path: |
            ~/android/.gradle
            ~/.gradle/cache
            # ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ env.cache-number }}-${{ hashFiles('android/build.gradle') }}-${{ hashFiles('android/app/build.gradle') }}
          restore-keys: |
            ${{ runner.os }}-gradle-${{ env.cache-name }}-${{ hashFiles('android/build.gradle') }}
            ${{ runner.os }}-gradle-${{ env.cache-name }}-
            ${{ runner.os }}-gradle-
            ${{ runner.os }}-

      - name: Cache Flutter modules
        uses: actions/cache@v3.0.1
        env:
          cache-number: ${{ secrets.CACHE_NUMBER }}
        with:
          path: |
            /Users/runner/hostedtoolcache/flutter
            # ~/.pub-cache
          key: ${{ runner.os }}-pub-${{ env.cache-number }}-${{ env.flutter_version }}-${{ hashFiles('pubspec.lock') }}
          restore-keys: |
            ${{ runner.os }}-pub-${{ env.flutter_version }}-
            ${{ runner.os }}-pub-
            ${{ runner.os }}-

      - name: Get flutter dependencies.
        run: make deps

#      - name: Check for any formatting and statically analyze the code.
#        run: make format-analyze

      - name: Build
        run: |
          make build-android
